name: nautobot-floor-plan
services:
  beat:
    depends_on:
      nautobot:
        condition: service_healthy
        required: true
    entrypoint:
      - sh
      - -c
      - watchmedo auto-restart --directory './' --pattern '*.py' --recursive -- nautobot-server celery beat -l $$NAUTOBOT_LOG_LEVEL
    environment:
      MYSQL_DATABASE: nautobot
      MYSQL_PASSWORD: changeme
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_USER: nautobot
      NAUTOBOT_ALLOWED_HOSTS: '*'
      NAUTOBOT_BANNER_TOP: Local
      NAUTOBOT_CHANGELOG_RETENTION: "0"
      NAUTOBOT_CREATE_SUPERUSER: "true"
      NAUTOBOT_DB_HOST: db
      NAUTOBOT_DB_NAME: nautobot
      NAUTOBOT_DB_PASSWORD: changeme
      NAUTOBOT_DB_TIMEOUT: "300"
      NAUTOBOT_DB_USER: nautobot
      NAUTOBOT_DEBUG: "True"
      NAUTOBOT_LOG_LEVEL: DEBUG
      NAUTOBOT_MAX_PAGE_SIZE: "0"
      NAUTOBOT_METRICS_ENABLED: "True"
      NAUTOBOT_NAPALM_PASSWORD: ""
      NAUTOBOT_NAPALM_TIMEOUT: "5"
      NAUTOBOT_NAPALM_USERNAME: ""
      NAUTOBOT_REDIS_HOST: redis
      NAUTOBOT_REDIS_PASSWORD: changeme
      NAUTOBOT_REDIS_PORT: "6379"
      NAUTOBOT_SECRET_KEY: changeme
      NAUTOBOT_SUPERUSER_API_TOKEN: 0123456789abcdef0123456789abcdef01234567
      NAUTOBOT_SUPERUSER_EMAIL: admin@example.com
      NAUTOBOT_SUPERUSER_NAME: admin
      NAUTOBOT_SUPERUSER_PASSWORD: admin
      PGPASSWORD: changeme
      POSTGRES_DB: nautobot
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: nautobot
    healthcheck:
      disable: true
    image: nautobot-floor-plan/nautobot:2.0.0-py3.11
    networks:
      default: null
    tty: true
    volumes:
      - type: bind
        source: /Users/djhoward/Documents/NTC/nautobot-app-floor-plan/development/nautobot_config.py
        target: /opt/nautobot/nautobot_config.py
        bind:
          create_host_path: true
      - type: bind
        source: /Users/djhoward/Documents/NTC/nautobot-app-floor-plan
        target: /source
        bind:
          create_host_path: true
  db:
    command:
      - -c
      - max_connections=200
    environment:
      MYSQL_DATABASE: nautobot
      MYSQL_PASSWORD: changeme
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_USER: nautobot
      NAUTOBOT_ALLOWED_HOSTS: '*'
      NAUTOBOT_BANNER_TOP: Local
      NAUTOBOT_CHANGELOG_RETENTION: "0"
      NAUTOBOT_CREATE_SUPERUSER: "true"
      NAUTOBOT_DB_HOST: db
      NAUTOBOT_DB_NAME: nautobot
      NAUTOBOT_DB_PASSWORD: changeme
      NAUTOBOT_DB_TIMEOUT: "300"
      NAUTOBOT_DB_USER: nautobot
      NAUTOBOT_DEBUG: "True"
      NAUTOBOT_LOG_LEVEL: DEBUG
      NAUTOBOT_MAX_PAGE_SIZE: "0"
      NAUTOBOT_METRICS_ENABLED: "True"
      NAUTOBOT_NAPALM_PASSWORD: ""
      NAUTOBOT_NAPALM_TIMEOUT: "5"
      NAUTOBOT_NAPALM_USERNAME: ""
      NAUTOBOT_REDIS_HOST: redis
      NAUTOBOT_REDIS_PASSWORD: changeme
      NAUTOBOT_REDIS_PORT: "6379"
      NAUTOBOT_SECRET_KEY: changeme
      NAUTOBOT_SUPERUSER_API_TOKEN: 0123456789abcdef0123456789abcdef01234567
      NAUTOBOT_SUPERUSER_EMAIL: admin@example.com
      NAUTOBOT_SUPERUSER_NAME: admin
      NAUTOBOT_SUPERUSER_PASSWORD: admin
      PGPASSWORD: changeme
      POSTGRES_DB: nautobot
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: nautobot
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready --username=$$POSTGRES_USER --dbname=$$POSTGRES_DB
      timeout: 5s
      interval: 10s
      retries: 10
    image: postgres:13-alpine
    networks:
      default: null
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
        volume: {}
  docs:
    entrypoint:
      - mkdocs
      - serve
      - -v
      - -a
      - 0.0.0.0:8080
    healthcheck:
      disable: true
    image: nautobot-floor-plan/nautobot:2.0.0-py3.11
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "8001"
        protocol: tcp
    tty: true
    volumes:
      - type: bind
        source: /Users/djhoward/Documents/NTC/nautobot-app-floor-plan
        target: /source
        bind:
          create_host_path: true
  nautobot:
    build:
      context: /Users/djhoward/Documents/NTC/nautobot-app-floor-plan
      dockerfile: development/Dockerfile
      args:
        NAUTOBOT_VER: 2.0.0
        PYTHON_VER: "3.11"
    command:
      - nautobot-server
      - runserver
      - 0.0.0.0:8080
    depends_on:
      db:
        condition: service_healthy
        required: true
      redis:
        condition: service_started
        required: true
    environment:
      MYSQL_DATABASE: nautobot
      MYSQL_PASSWORD: changeme
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_USER: nautobot
      NAUTOBOT_ALLOWED_HOSTS: '*'
      NAUTOBOT_BANNER_TOP: Local
      NAUTOBOT_CHANGELOG_RETENTION: "0"
      NAUTOBOT_CREATE_SUPERUSER: "true"
      NAUTOBOT_DB_ENGINE: django.db.backends.postgresql
      NAUTOBOT_DB_HOST: db
      NAUTOBOT_DB_NAME: nautobot
      NAUTOBOT_DB_PASSWORD: changeme
      NAUTOBOT_DB_TIMEOUT: "300"
      NAUTOBOT_DB_USER: nautobot
      NAUTOBOT_DEBUG: "True"
      NAUTOBOT_LOG_LEVEL: DEBUG
      NAUTOBOT_MAX_PAGE_SIZE: "0"
      NAUTOBOT_METRICS_ENABLED: "True"
      NAUTOBOT_NAPALM_PASSWORD: ""
      NAUTOBOT_NAPALM_TIMEOUT: "5"
      NAUTOBOT_NAPALM_USERNAME: ""
      NAUTOBOT_REDIS_HOST: redis
      NAUTOBOT_REDIS_PASSWORD: changeme
      NAUTOBOT_REDIS_PORT: "6379"
      NAUTOBOT_SECRET_KEY: changeme
      NAUTOBOT_SUPERUSER_API_TOKEN: 0123456789abcdef0123456789abcdef01234567
      NAUTOBOT_SUPERUSER_EMAIL: admin@example.com
      NAUTOBOT_SUPERUSER_NAME: admin
      NAUTOBOT_SUPERUSER_PASSWORD: admin
      PGPASSWORD: changeme
      POSTGRES_DB: nautobot
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: nautobot
    healthcheck:
      test:
        - CMD
        - "true"
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 1m0s
    image: nautobot-floor-plan/nautobot:2.0.0-py3.11
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
    tty: true
    volumes:
      - type: bind
        source: /Users/djhoward/Documents/NTC/nautobot-app-floor-plan/development/nautobot_config.py
        target: /opt/nautobot/nautobot_config.py
        bind:
          create_host_path: true
      - type: bind
        source: /Users/djhoward/Documents/NTC/nautobot-app-floor-plan
        target: /source
        bind:
          create_host_path: true
  redis:
    command:
      - sh
      - -c
      - redis-server --appendonly yes --requirepass $$NAUTOBOT_REDIS_PASSWORD
    environment:
      MYSQL_DATABASE: nautobot
      MYSQL_PASSWORD: changeme
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_USER: nautobot
      NAUTOBOT_ALLOWED_HOSTS: '*'
      NAUTOBOT_BANNER_TOP: Local
      NAUTOBOT_CHANGELOG_RETENTION: "0"
      NAUTOBOT_CREATE_SUPERUSER: "true"
      NAUTOBOT_DB_HOST: db
      NAUTOBOT_DB_NAME: nautobot
      NAUTOBOT_DB_PASSWORD: changeme
      NAUTOBOT_DB_TIMEOUT: "300"
      NAUTOBOT_DB_USER: nautobot
      NAUTOBOT_DEBUG: "True"
      NAUTOBOT_LOG_LEVEL: DEBUG
      NAUTOBOT_MAX_PAGE_SIZE: "0"
      NAUTOBOT_METRICS_ENABLED: "True"
      NAUTOBOT_NAPALM_PASSWORD: ""
      NAUTOBOT_NAPALM_TIMEOUT: "5"
      NAUTOBOT_NAPALM_USERNAME: ""
      NAUTOBOT_REDIS_HOST: redis
      NAUTOBOT_REDIS_PASSWORD: changeme
      NAUTOBOT_REDIS_PORT: "6379"
      NAUTOBOT_SECRET_KEY: changeme
      NAUTOBOT_SUPERUSER_API_TOKEN: 0123456789abcdef0123456789abcdef01234567
      NAUTOBOT_SUPERUSER_EMAIL: admin@example.com
      NAUTOBOT_SUPERUSER_NAME: admin
      NAUTOBOT_SUPERUSER_PASSWORD: admin
      PGPASSWORD: changeme
      POSTGRES_DB: nautobot
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: nautobot
    image: redis:6-alpine
    networks:
      default: null
  worker:
    depends_on:
      nautobot:
        condition: service_healthy
        required: true
    entrypoint:
      - sh
      - -c
      - watchmedo auto-restart --directory './' --pattern '*.py' --recursive -- nautobot-server celery worker -l $$NAUTOBOT_LOG_LEVEL --events
    environment:
      MYSQL_DATABASE: nautobot
      MYSQL_PASSWORD: changeme
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_USER: nautobot
      NAUTOBOT_ALLOWED_HOSTS: '*'
      NAUTOBOT_BANNER_TOP: Local
      NAUTOBOT_CHANGELOG_RETENTION: "0"
      NAUTOBOT_CREATE_SUPERUSER: "true"
      NAUTOBOT_DB_HOST: db
      NAUTOBOT_DB_NAME: nautobot
      NAUTOBOT_DB_PASSWORD: changeme
      NAUTOBOT_DB_TIMEOUT: "300"
      NAUTOBOT_DB_USER: nautobot
      NAUTOBOT_DEBUG: "True"
      NAUTOBOT_LOG_LEVEL: DEBUG
      NAUTOBOT_MAX_PAGE_SIZE: "0"
      NAUTOBOT_METRICS_ENABLED: "True"
      NAUTOBOT_NAPALM_PASSWORD: ""
      NAUTOBOT_NAPALM_TIMEOUT: "5"
      NAUTOBOT_NAPALM_USERNAME: ""
      NAUTOBOT_REDIS_HOST: redis
      NAUTOBOT_REDIS_PASSWORD: changeme
      NAUTOBOT_REDIS_PORT: "6379"
      NAUTOBOT_SECRET_KEY: changeme
      NAUTOBOT_SUPERUSER_API_TOKEN: 0123456789abcdef0123456789abcdef01234567
      NAUTOBOT_SUPERUSER_EMAIL: admin@example.com
      NAUTOBOT_SUPERUSER_NAME: admin
      NAUTOBOT_SUPERUSER_PASSWORD: admin
      PGPASSWORD: changeme
      POSTGRES_DB: nautobot
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: nautobot
    healthcheck:
      test:
        - CMD
        - "true"
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 30s
    image: nautobot-floor-plan/nautobot:2.0.0-py3.11
    networks:
      default: null
    tty: true
    volumes:
      - type: bind
        source: /Users/djhoward/Documents/NTC/nautobot-app-floor-plan/development/nautobot_config.py
        target: /opt/nautobot/nautobot_config.py
        bind:
          create_host_path: true
      - type: bind
        source: /Users/djhoward/Documents/NTC/nautobot-app-floor-plan
        target: /source
        bind:
          create_host_path: true
networks:
  default:
    name: nautobot-floor-plan_default
volumes:
  postgres_data:
    name: nautobot-floor-plan_postgres_data
x-nautobot-base:
  env_file:
    - development.env
    - creds.env
  image: nautobot-floor-plan/nautobot:2.0.0-py3.11
  tty: true
x-nautobot-build:
  build:
    args:
      NAUTOBOT_VER: 2.0.0
      PYTHON_VER: "3.11"
    context: ../
    dockerfile: development/Dockerfile
